### ISSUE TITLE
RSS feed crawling

### ISSUE THREAD

**Issue by Mec-iS** [SpaceAppsXploration/rdfendpoints#10]
Take a look to [this presentation](http://pixelmonkey.org/pub/python-crawling-slides/) to have some starting concepts.

PROBLEM: 
- We need to daily fetch and index RSS feeds from different Aerospace/Physics sources
- This index has in some way to be connected, or use the terms, listed in [ChronosAPI](http://ontology.projectchronos.eu/chronosapi/)
- This index has to serve data to [Xploration App in the 1st and 3rd stage](https://github.com/SpaceAppsXploration/rdfendpoints/wiki/The-Xploration-App)

POSSIBLE SOLUTIONS:
- [Microblog crawler](https://pypi.python.org/pypi/MicroblogCrawler)
- [scrapy](http://scrapy.org/)
- [Indexer](https://github.com/sidchilling/Indexer)

We have already 2500 articles taken from ESA and NASA websites indexed by keywords. So if we start to crawl news, we already have a good background.

**Comment by Mec-iS** [comment]
@mr-niels-christensen you can take a look the first [example of RSS-feed crawling](https://github.com/SpaceAppsXploration/rdfendpoints/blob/master/scripts/remote/feedcrawl.py). How would you implement it as a feature? Which datastore model? 
As it is now the library, the crawler keeps being up to look for updates from the given feeds. 

Also, I would like to pass all the links crawled into something like this [indexer](https://github.com/sidchilling/Indexer/blob/master/indexer_script.py) and store the resulting mapping as well.

**Comment by mr-niels-christensen** [comment]
To begin with the second part (indexing), I would recommend to use https://cloud.google.com/appengine/docs/python/search/ instead of the indexer_script.py
I think all relevant functionality is contained in GAE's own search API.

**Comment by mr-niels-christensen** [comment]
I doubt the `microblog_crawler` will run on GAE, because it builds on `multiprocessing.Pool`. I think `multiprocessing` will be disabled on GAE.

**Comment by mr-niels-christensen** [comment]
If this code works:
http://tuhrig.de/writing-an-online-scraper-on-google-app-engine-python/
then I would suggest adding a daily cron job activating the feed crawl, see https://cloud.google.com/appengine/docs/python/config/cron

**Comment by Mec-iS** [comment]
Ok, We have to enhance it:
1. to use BeautifulSoup4, the HTML/XML parser for DOM traversing
2. to implement an indexing script, that probably will need its model and entities (a map word>urls). @sidchilling accepted to help us.

**Comment by Mec-iS** [comment]
[First example pushed](https://github.com/SpaceAppsXploration/rdfendpoints/blob/master/flankers/Scrawler.py), to make initial tests

**Comment by Mec-iS** [comment]
A very [basic feature is implemented](https://github.com/SpaceAppsXploration/rdfendpoints/blob/master/flankers/Scrawler.py), you can test it locally by running the cronjob from the admin panel.

**Comment by Mec-iS** [comment]
Encoding Problem [here](https://github.com/SpaceAppsXploration/rdfendpoints/blob/master/datastore/models.py#L193): 

```
STORING: http://funcube.org.uk/2015/01/05/funcube-2-update-january-2015/
Cannot Store: 'ascii' codec can't encode character u'\u2013' in position 17: ordinal not in range(128)http://funcube.org.uk/2015/01/05/funcube-2-update-january-2015/
```

EDITED: Solved with [commit 72](https://github.com/SpaceAppsXploration/rdfendpoints/commit/e922d4a5057a44821b446652e7ffd696e940daa8)

**Comment by mr-niels-christensen** [comment]
Another option would be to let the data stay unicode rather than encode it into ascii?

**Comment by Mec-iS** [comment]
In our perspective the important I think is to use the Python way. Both Unicode and ASCII `unicode()s`  are encoded into `str()`  and stored in `StringProperty` in the datastore.

**Comment by Mec-iS** [comment]
First round of feeds have been stored in the WebResource model (crawled feeds are the ones with keyword=None, the others are webpages). Time to start thinking about Datastore Quota...
