### ISSUE TITLE
Visualize articles

### ISSUE THREAD

**Issue by Mec-iS** [SpaceAppsXploration/rdfendpoints#12]
I uploaded 2000+ indexed articles from NASA and ESA in GAE Datastore.

It would be nice, as a start, to have a simple "search engine" with autocompletion in which the user can type a keyword (see the 'keyword' property in the WebResource model) and the related articles show up.

I found this library to be quite interesting for tables filtering also: http://www.listjs.com/ maybe it can be implemented.

By now you can see a raw list of all the articles at [/visualize/articles/](http://rdfendpoints.appspot.com/visualize/articles/)

PS. Keywords are taken from the NASA-STI taxonomy and are the same used by [Chronos Concepts API](http://ontology.projectchronos.eu/chronosapi/aHR0cDovL2Nocm9ub3NhcGktY2hyb25vc2xvZC5yaGNsb3VkLmNvbS9jb25jZXB0cy9j)

**Comment by mr-niels-christensen** [comment]
I could probably prototype search completion using Typeahead by simply loading all keywords in the browser.

Step 2 would then be to make it scaleable by performing an actual search in an index.

**Comment by mr-niels-christensen** [comment]
@Mec-iS Do you have a way to get some of those articles into my local app instance for testing?

**Comment by mr-niels-christensen** [comment]
OK, actually I could probably download the data from appengine.

**Comment by mr-niels-christensen** [comment]
Note: To download data, I will need

```
builtins:
- remote_api: on
```

added in `app.yaml`, see https://cloud.google.com/appengine/docs/python/tools/remoteapi

**Comment by Mec-iS** [comment]
The autocomplete in the search input works, it needs a "Search" button and the handler for a POST to retrieve the selected articles. 

NOTE: implement memcache for:
- `GET /database/keywords` > returns the JSON with the full list of keywords 
- `POST /database/keywords params={'keyword': <something>}` > returns the articles indexed with the given keyword

**Comment by mr-niels-christensen** [comment]
Agree :)

**Comment by Mec-iS** [comment]
You can pull the keywords directly from the Chronos API:
http://chronosapi-chronoslod.rhcloud.com/concepts/c

Filter for property "group" = "keywords" 
Save a query! (;

**Comment by mr-niels-christensen** [comment]
OK! One concern is that (as I recall, I'm not at my laptop) keywords for an
item aren't stored separately. I may need to change that to allow lookup.

**Comment by mr-niels-christensen** [comment]
Strike my last comment. On inspection I realize that a "keyword" often
consists of several English words separated by +.

**Comment by Mec-iS** [comment]
If you take it from the online API they have only words ('label' property), whitespaces and rounded parethesis. I used to slugify them by replacing whitespaces with +.

**Comment by Mec-iS** [comment]
Now the `/visualize/articles/` handler displays also crawled feeds.
We should focus in **a way to link all this information** to the Chronos API and to the RDF vocabularies.

**Comment by mr-niels-christensen** [comment]
I posted a small pull request to use http://chronosapi-chronoslod.rhcloud.com/concepts/c

@Mec-iS I'm currently unable to download WebResources and Indexers from rdfendpoints.appspot.com - any idea why? The Components and GraphShardsseem to download fine.

**Comment by Mec-iS** [comment]
@mr-niels-christensen To fetch WebResource you can use: http://hypermedia.projectchronos.eu/visualize/articles/?api=true

There is a 'next' property at the end of the object to paginate.

**Comment by mr-niels-christensen** [comment]
Note to self: To get test data, do

```
appcfg.py download_data --url=http://chronostriples.appspot.com/_ah/remote_api --filename=1455.sql3
echo XX | appcfg.py upload_data --url=http://localhost:8082/_ah/remote_api --filename=1455.sql3 --application=dev~chronostriples --email=foobar@nowhere.com --passin
```

**Comment by Mec-iS** [comment]
anything you want to note, you should use [the wiki in the deployment page](https://github.com/SpaceAppsXploration/rdfendpoints/wiki/Deployment-Guide)

**Comment by mr-niels-christensen** [comment]
Good point! Done.

**Comment by Mec-iS** [comment]
Implemented memcache and now the mini-api is complete with keywords: http://hypermedia.projectchronos.eu/visualize/articles/?api=true

**Comment by Mec-iS** [comment]
@pincopallino93 is preparing an Android app. See https://github.com/SpaceAppsXploration/android-xpreader

@Jason-Cooke is preparing a BackBoneJS app.
